// Code generated by protoc-gen-go. DO NOT EDIT.
// source: example2/proto/model/common.proto

package model

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type RespType int32

const (
	RespType_NONE    RespType = 0
	RespType_ASCEND  RespType = 1
	RespType_DESCEND RespType = 2
)

var RespType_name = map[int32]string{
	0: "NONE",
	1: "ASCEND",
	2: "DESCEND",
}
var RespType_value = map[string]int32{
	"NONE":    0,
	"ASCEND":  1,
	"DESCEND": 2,
}

func (x RespType) String() string {
	return proto.EnumName(RespType_name, int32(x))
}
func (RespType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_common_435cb73e49c838b2, []int{0}
}

type SayParam struct {
	Msg                  string   `protobuf:"bytes,1,opt,name=msg" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SayParam) Reset()         { *m = SayParam{} }
func (m *SayParam) String() string { return proto.CompactTextString(m) }
func (*SayParam) ProtoMessage()    {}
func (*SayParam) Descriptor() ([]byte, []int) {
	return fileDescriptor_common_435cb73e49c838b2, []int{0}
}
func (m *SayParam) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SayParam.Unmarshal(m, b)
}
func (m *SayParam) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SayParam.Marshal(b, m, deterministic)
}
func (dst *SayParam) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SayParam.Merge(dst, src)
}
func (m *SayParam) XXX_Size() int {
	return xxx_messageInfo_SayParam.Size(m)
}
func (m *SayParam) XXX_DiscardUnknown() {
	xxx_messageInfo_SayParam.DiscardUnknown(m)
}

var xxx_messageInfo_SayParam proto.InternalMessageInfo

func (m *SayParam) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

type Pair struct {
	Key                  int32    `protobuf:"varint,1,opt,name=key" json:"key,omitempty"`
	Values               string   `protobuf:"bytes,2,opt,name=values" json:"values,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Pair) Reset()         { *m = Pair{} }
func (m *Pair) String() string { return proto.CompactTextString(m) }
func (*Pair) ProtoMessage()    {}
func (*Pair) Descriptor() ([]byte, []int) {
	return fileDescriptor_common_435cb73e49c838b2, []int{1}
}
func (m *Pair) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Pair.Unmarshal(m, b)
}
func (m *Pair) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Pair.Marshal(b, m, deterministic)
}
func (dst *Pair) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Pair.Merge(dst, src)
}
func (m *Pair) XXX_Size() int {
	return xxx_messageInfo_Pair.Size(m)
}
func (m *Pair) XXX_DiscardUnknown() {
	xxx_messageInfo_Pair.DiscardUnknown(m)
}

var xxx_messageInfo_Pair proto.InternalMessageInfo

func (m *Pair) GetKey() int32 {
	if m != nil {
		return m.Key
	}
	return 0
}

func (m *Pair) GetValues() string {
	if m != nil {
		return m.Values
	}
	return ""
}

type SayResponse struct {
	Msg string `protobuf:"bytes,1,opt,name=msg" json:"msg,omitempty"`
	// 数组
	Values []string `protobuf:"bytes,2,rep,name=values" json:"values,omitempty"`
	// map
	Header               map[string]*Pair `protobuf:"bytes,3,rep,name=header" json:"header,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Type                 RespType         `protobuf:"varint,4,opt,name=type,enum=model.RespType" json:"type,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *SayResponse) Reset()         { *m = SayResponse{} }
func (m *SayResponse) String() string { return proto.CompactTextString(m) }
func (*SayResponse) ProtoMessage()    {}
func (*SayResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_common_435cb73e49c838b2, []int{2}
}
func (m *SayResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SayResponse.Unmarshal(m, b)
}
func (m *SayResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SayResponse.Marshal(b, m, deterministic)
}
func (dst *SayResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SayResponse.Merge(dst, src)
}
func (m *SayResponse) XXX_Size() int {
	return xxx_messageInfo_SayResponse.Size(m)
}
func (m *SayResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SayResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SayResponse proto.InternalMessageInfo

func (m *SayResponse) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func (m *SayResponse) GetValues() []string {
	if m != nil {
		return m.Values
	}
	return nil
}

func (m *SayResponse) GetHeader() map[string]*Pair {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *SayResponse) GetType() RespType {
	if m != nil {
		return m.Type
	}
	return RespType_NONE
}

type SRequest struct {
	Count                int64    `protobuf:"varint,1,opt,name=count" json:"count,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SRequest) Reset()         { *m = SRequest{} }
func (m *SRequest) String() string { return proto.CompactTextString(m) }
func (*SRequest) ProtoMessage()    {}
func (*SRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_common_435cb73e49c838b2, []int{3}
}
func (m *SRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SRequest.Unmarshal(m, b)
}
func (m *SRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SRequest.Marshal(b, m, deterministic)
}
func (dst *SRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SRequest.Merge(dst, src)
}
func (m *SRequest) XXX_Size() int {
	return xxx_messageInfo_SRequest.Size(m)
}
func (m *SRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SRequest proto.InternalMessageInfo

func (m *SRequest) GetCount() int64 {
	if m != nil {
		return m.Count
	}
	return 0
}

type SResponse struct {
	Value                []string `protobuf:"bytes,1,rep,name=value" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SResponse) Reset()         { *m = SResponse{} }
func (m *SResponse) String() string { return proto.CompactTextString(m) }
func (*SResponse) ProtoMessage()    {}
func (*SResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_common_435cb73e49c838b2, []int{4}
}
func (m *SResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SResponse.Unmarshal(m, b)
}
func (m *SResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SResponse.Marshal(b, m, deterministic)
}
func (dst *SResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SResponse.Merge(dst, src)
}
func (m *SResponse) XXX_Size() int {
	return xxx_messageInfo_SResponse.Size(m)
}
func (m *SResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SResponse proto.InternalMessageInfo

func (m *SResponse) GetValue() []string {
	if m != nil {
		return m.Value
	}
	return nil
}

func init() {
	proto.RegisterType((*SayParam)(nil), "model.SayParam")
	proto.RegisterType((*Pair)(nil), "model.Pair")
	proto.RegisterType((*SayResponse)(nil), "model.SayResponse")
	proto.RegisterMapType((map[string]*Pair)(nil), "model.SayResponse.HeaderEntry")
	proto.RegisterType((*SRequest)(nil), "model.SRequest")
	proto.RegisterType((*SResponse)(nil), "model.SResponse")
	proto.RegisterEnum("model.RespType", RespType_name, RespType_value)
}

func init() {
	proto.RegisterFile("example2/proto/model/common.proto", fileDescriptor_common_435cb73e49c838b2)
}

var fileDescriptor_common_435cb73e49c838b2 = []byte{
	// 311 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x91, 0xdd, 0x4a, 0xc3, 0x40,
	0x10, 0x85, 0xdd, 0xe6, 0xc7, 0x74, 0x02, 0x5a, 0x96, 0x22, 0x41, 0x44, 0xd2, 0x78, 0x53, 0x04,
	0x53, 0x89, 0x20, 0xe2, 0x9d, 0xd8, 0x88, 0x57, 0xb5, 0x6c, 0x7c, 0x81, 0xb5, 0x1d, 0x54, 0xec,
	0x66, 0x63, 0x92, 0x8a, 0xfb, 0xae, 0x3e, 0x8c, 0x64, 0x92, 0x6a, 0xc5, 0xbb, 0x3d, 0x73, 0xe6,
	0x1c, 0xe6, 0x63, 0x61, 0x84, 0x9f, 0x52, 0x15, 0x2b, 0x4c, 0x26, 0x45, 0xa9, 0x6b, 0x3d, 0x51,
	0x7a, 0x89, 0xab, 0xc9, 0x42, 0x2b, 0xa5, 0xf3, 0x98, 0x46, 0xdc, 0xa1, 0x59, 0x74, 0x04, 0x5e,
	0x26, 0xcd, 0x5c, 0x96, 0x52, 0xf1, 0x01, 0x58, 0xaa, 0x7a, 0x0e, 0x58, 0xc8, 0xc6, 0x7d, 0xd1,
	0x3c, 0xa3, 0x73, 0xb0, 0xe7, 0xf2, 0xb5, 0x6c, 0x9c, 0x37, 0x34, 0xe4, 0x38, 0xa2, 0x79, 0xf2,
	0x03, 0x70, 0x3f, 0xe4, 0x6a, 0x8d, 0x55, 0xd0, 0xa3, 0xf5, 0x4e, 0x45, 0x5f, 0x0c, 0xfc, 0x4c,
	0x1a, 0x81, 0x55, 0xa1, 0xf3, 0x0a, 0xff, 0x77, 0xfe, 0x49, 0x5a, 0xbf, 0x49, 0x7e, 0x09, 0xee,
	0x0b, 0xca, 0x25, 0x96, 0x81, 0x15, 0x5a, 0x63, 0x3f, 0x39, 0x8e, 0xe9, 0xc2, 0x78, 0xab, 0x2d,
	0xbe, 0xa7, 0x85, 0x34, 0xaf, 0x4b, 0x23, 0xba, 0x6d, 0x7e, 0x02, 0x76, 0x6d, 0x0a, 0x0c, 0xec,
	0x90, 0x8d, 0xf7, 0x92, 0xfd, 0x2e, 0xd5, 0x44, 0x1e, 0x4d, 0x81, 0x82, 0xcc, 0xc3, 0x3b, 0xf0,
	0xb7, 0xb2, 0xdb, 0x3c, 0xfd, 0x96, 0x67, 0x04, 0x0e, 0xdd, 0x41, 0x38, 0x7e, 0xe2, 0x77, 0x35,
	0x0d, 0xbd, 0x68, 0x9d, 0xeb, 0xde, 0x15, 0x8b, 0x42, 0xf0, 0x32, 0x81, 0xef, 0x6b, 0xac, 0x6a,
	0x3e, 0x04, 0x67, 0xa1, 0xd7, 0x79, 0x4d, 0x35, 0x96, 0x68, 0x45, 0x34, 0x82, 0x7e, 0xf6, 0x43,
	0x3f, 0xdc, 0xb4, 0x32, 0x42, 0x6d, 0xc5, 0xe9, 0x19, 0x78, 0x9b, 0xf3, 0xb8, 0x07, 0xf6, 0xec,
	0x61, 0x96, 0x0e, 0x76, 0x38, 0x80, 0x7b, 0x93, 0xdd, 0xa6, 0xb3, 0xe9, 0x80, 0x71, 0x1f, 0x76,
	0xa7, 0x69, 0x2b, 0x7a, 0x4f, 0x2e, 0x7d, 0xd8, 0xc5, 0x77, 0x00, 0x00, 0x00, 0xff, 0xff, 0x55,
	0x9c, 0x27, 0x91, 0xd5, 0x01, 0x00, 0x00,
}
